development:
  sessions:
    default:
      database: apis_development
      hosts:
        - localhost:27017
      options:
  options:
production:
  sessions:
    default:
      database: apis
      hosts:
        - <%= ENV['MONGODB_PORT_27017_TCP_ADDR'] %>:27017
      options:
  options:
test:
  sessions:
    default:
      database: api_through_ui_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
